- hosts: all
  sudo: yes
  roles:
    - { role: bahmni-base }
    - { role: bahmni-repo-management, enabled: 1 }
    - { role: bahmni-user }
    - { role: installer-config }
    - { role: bahmni-support-user, tags: support-user }
    - { role: selinux, selinux_state: permissive, selinux_policy: targeted }
  tags:
    - setup

- hosts: bahmni-emr-db:bahmni-emr-db-slave
  sudo: yes
  roles:
    - { role: mysql }
  tags:
    - bahmni-emr-db
    - bahmni-emr

- hosts: bahmni-emr
  sudo: yes
  roles:
    - { role: bahmni-emr }
    - { role: bahmni-web }
    - { role: bahmni-certs }
    - { role: httpd }
  tags:
    - bahmni-emr

- hosts: bahmni-emr
  sudo: yes
  roles:
    - { role: implementation-config}
  tags:
    - config

- hosts: bahmni-reports
  sudo: yes
  roles:
    - { role: bahmni-reports }
  tags:
    - bahmni-reports

- hosts: bahmni-erp-db:bahmni-erp-db-slave
  sudo: yes
  roles:
    - { role: postgres, postgres_user: openerp }
  tags:
    - bahmni-erp-db
    - bahmni-erp

- hosts: bahmni-erp
  sudo: yes
  roles:
    - { role: bahmni-erp }
  tags:
    - bahmni-erp

- hosts: bahmni-erp
  sudo: yes
  roles:
    - { role: bahmni-erp-connect }
  tags:
    - bahmni-erp-connect

- hosts: bahmni-lab-db:bahmni-lab-db-slave
  sudo: yes
  roles:
    - { role: postgres, postgres_user: clinlims }
  tags:
    - bahmni-lab-db
    - bahmni-lab

- hosts: bahmni-lab
  sudo: yes
  roles:
    - { role: bahmni-lab }
  tags:
    - bahmni-lab

- hosts: bahmni-emr
  sudo: yes
  roles:
    - { role: bahmni-lab-connect, when: "{{ groups['bahmni-lab'] | length }} > 0" }
  tags:
    - bahmni-lab-connect

- hosts: bahmni-pacs
  sudo: yes
  roles:
    - { role: bahmni-pacs }
  tags:
    - bahmni-pacs

- hosts: dcm4chee
  sudo: yes
  roles:
    - { role: dcm4chee }
  tags:
    - dcm4chee

- hosts: bahmni-event-log-service
  sudo: yes
  roles:
    - { role: bahmni-event-log-service }
  tags:
    - event-log

- hosts: bahmni-emr
  sudo: yes
  roles:
   - { role: bahmni-support-user }
  tags:
   - support-user

- hosts: all
  sudo: yes
  roles:
   - { role: bahmni-repo-management, enabled: 0 }

