- name: Check if pacs-integration rpm needs an update
  command: yum list installed pacs-integration
  register: installed_pacs_integration
  ignore_errors: true

- name: Uninstall pacs-integration rpm
  yum: name="pacs-integration" state=absent
  when: installed_pacs_integration.stdout.find("{{ pacs_integration_version }}") == -1

- name: Install pacs-integration from bahmni-repo
  yum: name="pacs-integration-{{ pacs_integration_version }}" state=present

- name: Copy bahmni-pacs config
  template:
    src=bahmni-pacs.conf.j2
    dest=/opt/bahmni-pacs/etc/bahmni-pacs.conf
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy oviyam2-1 config
  template:
    src=oviyam2-1-config.xml.j2
    dest=/opt/bahmni-pacs/etc/oviyam2-1-config.xml
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Copy atomfeed properties
  template:
    src=atomfeed.properties.j2
    dest=/opt/bahmni-pacs/pacs-integration/WEB-INF/classes/atomfeed.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Get matched IpTable rule
  shell: iptables -nL --line-numbers | grep BAHMNIPACS  -m 1 | cut -c 1-2
  register: matchedRule

- name: delete matching rule if exists
  shell: iptables -D INPUT {{ matchedRule.stdout }}
  when: matchedRule.stdout!=""

- name: Allow bahmni-pacs port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  {{ bahmni_pacs_port }} -j ACCEPT -m comment --comment "BAHMNIPACS"

- name: save iptables
  command: service iptables save

- name: Switch off chkconfig for bahmni-pacs on passive
  service: name=bahmni-pacs state=stopped enabled=no
  when: passive is defined and passive == 'yes'

- name: Stop bahmni-pacs
  service:
    name=bahmni-pacs
    state=stopped
  when: passive is not defined or passive != 'yes'
  tags: stop_bahmni

- name: Start bahmni-pacs and enable at boot
  service:
    name=bahmni-pacs
    enabled=yes
    state=started
  when: passive is not defined or passive != 'yes'
  tags: start_bahmni

- name: Check bahmni-pacs
  command: service bahmni-pacs status
  when: passive is not defined or passive != 'yes'
  tags: check_status
