- name: Install python-gdata
  yum: name=python-gdata-2.0.11-1.el6.noarch state=present

- name: install nonblockingloghandler
  pip: name=nonblockingloghandler state=present

- name: Check if postgres yum repo rpm is present
  stat: path={{postgres_repo_rpm_location}}
  register: postgresRepoRpm

- name: Download postgres yum repo rpm if not present
  command: "wget -q -O {{ postgres_repo_rpm_location }} {{postgres_repo_download_url}} creates={{ postgres_repo_rpm_location }}"
  when: postgresRepoRpm.stat.exists == false

- name: Install postgresql yum repository
  yum: name={{postgres_repo_rpm_location}} state=present

- name: Install python-psycopg2
  yum: name=python-psycopg2 state=present

- name: Check if bahmni-erp rpm needs an update
  command: yum list installed bahmni-erp
  register: installed_bahmni_erp
  ignore_errors: true

- name: Uninstall bahmni-erp rpm
  yum: name="bahmni-erp" state=absent
  when: installed_bahmni_erp.stdout.find("{{ bahmni_erp_version }}") == -1

- name: Install bahmni-erp from bahmni-repo
  yum: name="bahmni-erp-{{ bahmni_erp_version }}" state=present

- name: Copy openerp server template
  template: src=openerp-server.conf.j2 dest=/etc/openerp/openerp-server.conf owner=openerp group=openerp mode=0655

- name: Get matched IpTable rule
  shell: iptables -nL --line-numbers | grep BAHMNIERP  -m 1 | cut -c 1-2
  register: matchedRule

- name: delete matching rule if exists
  shell: iptables -D INPUT {{ matchedRule.stdout }}
  when: matchedRule.stdout!=""

- name: Allow openerp port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  {{ openerp_port }} -j ACCEPT -m comment --comment "BAHMNIERP"

- name: save iptables
  command: service iptables save

- name: Switch off chkconfig for Openerp on passive
  service: name=openerp state=stopped enabled=no
  when: passive is defined and passive == 'yes'

- name: Stop Openerp
  service:
    name=openerp
    state=stopped
  when: passive is not defined or passive != 'yes'
  tags: stop_bahmni

- name: Start Openerp and enable at boot
  service:
    name=openerp
    enabled=yes
    state=started
  when: passive is not defined or passive != 'yes'
  tags: start_bahmni


