openmrs_port: 8080
bahmni_lab_port: 8081
bahmni_reports_port: 8083
openerp_port: 8069
oviyam2_port: 8085
patient_document_max_age: 86400
apps_max_age: 1
SSLCertificateFilePath: /opt/bahmni-certs/certs/cert.pem
SSLCertificateKeyFilePath: /opt/bahmni-certs/certs/privkey.pem
SSLCertificateChainFilePath: /opt/bahmni-certs/certs/chain.pem
