- name: check if java is already downloaded
  stat: path={{java_file_url}}
  register: downloaded_java

- name: install oracle java rpm
  yum: name={{ java_file_url }} state=present

- name: set java_role_ran fact
  set_fact:
    java_role_ran: true
