- name: Check if bahmni-erp-connect rpm needs an update
  command: yum list installed bahmni-erp-connect
  register: installed_bahmni_erp_connect
  ignore_errors: true

- name: Unintall bahmni-erp-connect rpm
  yum: name="bahmni-erp-connect" state=absent
  when: installed_bahmni_erp_connect.stdout.find("{{ bahmni_erp_connect_version }}") == -1

- name: Install bahmni-erp-connect from bahmni-repo
  yum: name="bahmni-erp-connect-{{ bahmni_erp_connect_version }}" state=present

- name: Copy bahmni-erp-connect configuration
  template:
    src=bahmni-erp-connect.conf.j2
    dest=/opt/bahmni-erp-connect/etc/bahmni-erp-connect.conf
    owner=bahmni
    group=bahmni
    mode=0644

- name: Switch off chkconfig for bahmni-openerp-connect on passive
  service: name=bahmni-erp-connect state=stopped enabled=no
  when: passive is defined and passive == 'yes'

- name: Stop bahmni-openerp-connect
  service:
    name=bahmni-erp-connect
    state=stopped
  when: passive is not defined or passive != 'yes'
  tags: stop_bahmni

- name: Start bahmni-openerp-connect and enable at boot
  service:
    name=bahmni-erp-connect
    enabled=yes
    state=started
  when: passive is not defined or passive != 'yes'
  tags: start_bahmni

- name: Check bahmni-openerp-connect
  command: service bahmni-erp-connect status
  when: passive is not defined or passive != 'yes'
  tags: check_status