- name: copy concepts
  copy:
    src: concepts
    dest: "{{ openmrs_install_dir }}/configuration"
    owner: bahmni

- name: copy forms
  copy:
    src: bahmniforms
    dest: "{{ openmrs_install_dir }}/configuration"
    owner: bahmni

- name: create translations directory
  file:
    path: "{{ bahmni_forms_translations_dir }}"
    state: directory

- name: copy form translations
  vars:
    bahmni_form_dir: "{{ openmrs_install_dir }}/configuration/bahmniforms"
  script:
    cmd: "publish_translations.py {{ bahmni_form_dir }} {{ bahmni_forms_translations_dir }}"

- name: allow all users to modify translations
  file:
    path: "{{ bahmni_forms_translations_dir }}"
    recurse: yes
    owner: bahmni
    mode: a+rwx

- name: ensure that the intializer is present in the correct version
  copy:
    src: initializer-2.0.0.omod
    dest:  "{{ openmrs_install_dir }}/modules/"
    owner: bahmni

# TODO: refactor later. avoid database conflicts
- name: update concept sources
  vars:
     update_script: "{{ lookup('file', 'concept_sources_helper.sql') }}"
  shell: echo {{ update_script | quote }} | mysql -u{{mysql_root_user}} -p{{mysql_root_password}} openmrs

- name: Restart openmrs
  service: name=openmrs state=restarted
