- name: copy concepts
  copy:
    src: concepts
    dest: "{{ openmrs_install_dir }}/configuration"
    owner: bahmni

- name: copy forms
  copy:
    src: bahmniforms
    dest: "{{ openmrs_install_dir }}/configuration"
    owner: bahmni

- name: ensure that the intializer is present in the correct version
  copy:
    src: initializer-2.0.0.omod
    dest:  "{{ openmrs_install_dir }}/modules/"
    owner: bahmni

# TODO: refactor later. avoid database conflicts
- name: update concept sources
  vars:
     update_script: "{{ lookup('file', 'concept_sources_helper.sql') }}"
  shell: echo {{ update_script | quote }} | mysql -u{{mysql_root_user}} -p{{mysql_root_password}} openmrs

- name: Restart openmrs
  service: name=openmrs state=restarted
